export const VIEW_URLS: Record<string, string> = {
  'community': '/',
  'chats': '/chats',
  'post-detail': '/post',
  'user-profile': '/profile',
  'learn_intro': '/learn/intro',
  'learn_choose_flute': '/learn/choose-flute',
  'learn_tuner': '/learn/tuner',
  'learn_basics': '/learn/basics',
  'learn_alankaras': '/learn/alankaras',
  'learn_raagas': '/learn/raagas',
  'community_members': '/members',
  'about_us': '/about',
  'contact_us': '/contact',
  'learn_dashboard': '/learn',
  'notation_requests': '/notations',
  'privacy_policy': '/privacy-policy',
  'terms_of_service': '/terms-of-service',
};
