export const VIEW_URLS: Record<string, string> = {
  'community': '/',
  'chats': '/chats',
  'post-detail': '/post',
  'user-profile': '/profile',
  'learn_intro': '/learn/intro',
  'learn_choose_flute': '/learn/choose-flute',
  'learn_tuner': '/tuner',
  'learn_basics': '/learn/basics',
  'learn_fingering_chart': '/learn/fingering-chart',
  'learn_alankaras': '/learn/alankaras',
  'alankar_generator': '/alankar-generator',
  'learn_raagas': '/learn/raagas',
  'raga_bhoopali': '/learn/raga-bhoopali',
  'raga_durga': '/learn/raga-durga',
  'raga_yaman': '/learn/raga-yaman',
  'community_members': '/members',
  'about_us': '/about',
  'contact_us': '/contact',
  'learn_dashboard': '/learn',
  'notation_requests': '/notations',
  'privacy_policy': '/privacy-policy',
  'terms_of_service': '/terms-of-service',
  'not_found': '/404',
};
