import { FaqItem } from '../components/FluteFaqView';

export const HEALTH_AND_BREATHING_FAQS: FaqItem[] = [
  {
    id: 'health-diaphragmatic-breathing-explained',
    category: 'Health & Breathing',
    question: 'What is diaphragmatic breathing and how does it power the flute?',
    answer: `Diaphragmatic breathing (commonly known as belly breathing) is the primary foundation of powerful, effortless air support for all wind instruments, particularly the bamboo bansuri.

How Diaphragmatic Breathing Operates:
• Inhalation Mechanics: As you inhale deeply, expand your lower abdomen outwards, allowing your dome-shaped diaphragm muscle to drop downwards and fill the lower lungs completely with air.
• Exhalation Mechanics: As you blow into the blow hole, gently engage your lower abdominal core muscles inward to propel a steady, pressurized air column into the instrument.
• Comparison with Shallow Chest Breathing: Shallow chest breathing expands only the upper ribcage, causing rapid physical fatigue, neck tightness, and unsteady, breathy air pressure.
• Core Benefits: Delivers rock-solid pitch stability, doubles sustained note duration, and keeps your neck, upper chest, and shoulders completely relaxed.`,
    relatedLink: { text: 'Read Bansuri Fundamentals & Breathing', view: 'learn_basics' },
    tags: ['diaphragmatic breathing', 'belly breathing', 'air support', 'stamina']
  },
  {
    id: 'health-correct-sitting-and-standing-posture',
    category: 'Health & Breathing',
    question: 'What is the correct posture for sitting and standing while playing the bansuri?',
    answer: `Maintaining optimal physical posture aligns your spine, vocal tract, and respiratory system, facilitating maximum lung expansion and uninhibited airflow.

Ergonomic Posture Guidelines:
• Cross-Legged Floor Seated (Sukhasana): Sit on a firm cushion with hips slightly elevated above knee level. Keep your spine erect but supple, with shoulders dropped naturally.
• Chair Seated Posture: Sit on the front edge of a firm chair with both feet flat on the floor, knees at a 90-degree angle, and back unsupported to keep core muscles engaged.
• Standing Posture: Stand with feet shoulder-width apart, knees slightly un-locked, and body weight evenly distributed across both feet.
• Head & Jaw Alignment: Keep your chin parallel to the floor—never tilt your head downwards toward the flute, as doing so compresses your trachea and muffles tone projection.`,
    relatedLink: { text: 'View Posture Guidelines', view: 'learn_basics' },
    tags: ['posture', 'sitting', 'standing', 'sukhasana', 'spine alignment']
  },
  {
    id: 'health-preventing-lip-fatigue-and-soreness',
    category: 'Health & Breathing',
    question: 'Why do my lips feel sore or fatigued, and how do I build embouchure stamina safely?',
    answer: `Experiencing lip muscle fatigue or mild soreness is completely normal for beginners as small facial muscles adapt to the novel demands of forming a precise lip embouchure.

Building Lip Stamina Safely:
• Muscle Adaptation Process: The facial muscles surrounding your lips (orbicularis oris) work in unfamiliar ways to maintain a narrow, focused oval lip aperture.
• Micro-Practice Strategy: Practice in 20-minute focused blocks rather than long, exhausting continuous marathons. Stop playing immediately if your lips begin trembling or feel numb.
• Zero Squeezing Pressure: Never press the bamboo flute tube tightly against your lower lip. Use minimal contact pressure—pure tone resonance is generated by air stream velocity and focus, not physical contact pressure.`,
    relatedLink: { text: 'Read Embouchure Basics', view: 'learn_basics' },
    tags: ['lip fatigue', 'embouchure stamina', 'facial muscles', 'sore lips']
  },
  {
    id: 'health-preventing-wrist-and-finger-pain',
    category: 'Health & Breathing',
    question: 'How do I prevent wrist soreness, finger joint stiffness, and RSI while practicing?',
    answer: `Hand, wrist, and finger discomfort during flute practice stems from holding physical tension, squeezing the bamboo, or maintaining awkward joint angles.

Preventing Hand Strain & Repetitive Strain Injuries (RSI):
• Flat Finger Pad Technique: Avoid curling fingers tightly into claws or pressing fingertips hard into wood. Use flat, relaxed finger pads (second phalange) over hole centers.
• Natural Wrist Extension: Keep your wrists gently curved in a natural, straight extension of your forearms—avoid bending wrists at sharp 90-degree angles.
• Frequent Rest Micro-Breaks: Rest for 5 minutes every 25 minutes. Lower your hands and gently shake out your fingers, wrists, and forearms to release accumulated muscle tension.`,
    relatedLink: { text: 'Read Common Beginner Pitfalls', view: 'learn_common_mistakes' },
    tags: ['wrist pain', 'finger stiffness', 'rsi', 'hand ergonomics', 'relaxation']
  },
  {
    id: 'health-building-lung-capacity',
    category: 'Health & Breathing',
    question: 'Can I increase my lung capacity through breathing exercises and lifestyle habits?',
    answer: `While anatomical lung size is fixed by genetics, you can significantly increase usable lung volume, diaphragm control, and breathing efficiency through targeted exercises.

Actionable Methods to Enhance Breathing Stamina:
• Yogic Pranayama Practices: Practice Anulom Vilom (alternate nostril breathing) and Kapalabhati daily to strengthen respiratory muscles and optimize oxygen exchange.
• Aerobic Cardiovascular Conditioning: Regular swimming, brisk walking, or cycling builds cardiovascular endurance and lung efficiency.
• Sustained Kharaj Sadhana: Holding long lower-octave notes daily trains your respiratory system to expel air with maximum control, efficiency, and zero waste.`,
    relatedLink: { text: 'Explore Daily Sadhana Blueprint', view: 'learn_daily_practice' },
    tags: ['lung capacity', 'pranayama', 'breathing exercises', 'endurance']
  },
  {
    id: 'health-stopping-dizziness-and-lightheadedness',
    category: 'Health & Breathing',
    question: 'Why do I feel dizzy or lightheaded when playing, and how do I prevent it?',
    answer: `Feeling lightheaded or dizzy during initial flute practice occurs when mild hyperventilation lowers carbon dioxide levels in your bloodstream due to improper blowing mechanics.

Causes & Instant Prevention Strategies:
• Common Root Cause: Beginners frequently expel air too rapidly or force breath without full diaphragmatic support, taking shallow, rapid inhalations.
• Immediate Action Step: Stop playing immediately, sit down comfortably, and take slow, normal nasal breaths until your head clears completely.
• Long-Term Solution: Focus on forming a smaller lip aperture to blow a thin, focused air stream, rather than dumping large volumes of loose air into the instrument.`,
    relatedLink: { text: 'Read Beginners Troubleshooting', view: 'learn_basics' },
    tags: ['dizziness', 'lightheadedness', 'hyperventilation', 'air focus']
  },
  {
    id: 'health-preventing-neck-and-shoulder-tension',
    category: 'Health & Breathing',
    question: 'Why do my neck and shoulders hurt during practice, and how do I fix my alignment?',
    answer: `Neck and shoulder tension is caused by hunching, raising shoulders toward your ears, or tilting your head sideways toward the flute.

Correcting Neck & Shoulder Alignment:
• Drop Your Shoulders: Periodically pause during practice and verify that your shoulders are dropped, relaxed, and resting away from your ears.
• Bring Flute to Lips: Bring the flute up to meet your lower lip naturally—never lower your chin down or tilt your neck sideways to reach the flute.
• Mirror Practice Checks: Practice in front of a mirror to catch shoulder elevation or neck tilting before it turns into chronic muscle strain.`,
    relatedLink: { text: 'View Posture & Alignment Blueprint', view: 'learn_basics' },
    tags: ['neck pain', 'shoulder tension', 'posture check', 'mirror alignment']
  },
  {
    id: 'health-practice-warmup-and-cooldown',
    category: 'Health & Breathing',
    question: 'What is an effective physical warm-up and cool-down routine for flute players?',
    answer: `Warming up and cooling down physical joints and respiratory muscles protects flutists from repetitive strain and enhances overall playing flexibility.

Physical Warm-Up & Cool-Down Routine:
• Pre-Practice Warm-Up (3 Minutes): Gently roll your shoulders backwards, stretch your neck side to side, flex and extend your wrists, and take 5 deep diaphragmatic breaths.
• Post-Practice Cool-Down (2 Minutes): Drop your arms to your sides, gently shake out your hands, stretch your finger flexors, and lightly massage your cheeks and jaw muscles.`,
    relatedLink: { text: 'Read Daily Practice Routine', view: 'learn_daily_practice' },
    tags: ['warmup', 'cooldown', 'stretching', 'injury prevention']
  },
  {
    id: 'health-hydration-and-lip-care',
    category: 'Health & Breathing',
    question: 'How does body hydration affect flute playing and lip embouchure performance?',
    answer: `Hydration directly impacts lip flexibility, air seal integrity, and facial comfort during flute practice sessions.

Hydration & Lip Care Guidelines:
• Effects of Dehydration: Dry or chapped lips create a rough contact surface against the blow hole, causing air leaks, skin irritation, and erratic pitch stability.
• Sip Water Frequently: Keep a water bottle handy and sip water throughout practice sessions to stay hydrated.
• Lip Balm Application: Apply a non-greasy, natural lip balm well before practice sessions so your lips remain soft, smooth, and supple without slipping on the bamboo blow hole.`,
    relatedLink: { text: 'Explore Flute Care & Health Tips', view: 'learn_basics' },
    tags: ['hydration', 'lip care', 'chapped lips', 'embouchure']
  },
  {
    id: 'health-playing-with-colds-and-allergies',
    category: 'Health & Breathing',
    question: 'Should I practice the flute when I have a common cold, sore throat, or nasal congestion?',
    answer: `Practicing while recovering from illness requires mindful self-awareness to protect your respiratory health.

Health Guidelines for Practicing When Sick:
• Sore Throat or Fever: Rest completely—do not force your respiratory system when throat or lung tissues are inflamed.
• Mild Nasal Congestion: Light long-note practice is acceptable and can actually open nasal passages gently, but avoid intense, high-octane speed sessions.
• Sanitize Your Flute: Always swab and sanitize your flute blow hole thoroughly with isopropyl alcohol wipes after practicing while recovering to prevent re-infection.`,
    relatedLink: { text: 'Read Flute Hygiene Guidelines', view: 'learn_basics' },
    tags: ['common cold', 'sore throat', 'health', 'hygiene']
  },
  {
    id: 'health-managing-performance-anxiety',
    category: 'Health & Breathing',
    question: 'How do I manage performance anxiety, rapid breathing, and shaky hands before playing?',
    answer: `Performance anxiety triggers "fight or flight" physiological responses that affect air control, heart rate, and hand stability before recitals.

Anxiety Management Strategies:
• Box Breathing Routine: Inhale for 4 seconds, hold breath for 4 seconds, exhale for 4 seconds, hold for 4 seconds. Repeat 4 cycles before stepping on stage to reset your nervous system.
• Focus on the Drone: Center your mind on the soothing frequency of the Tanpura drone rather than worrying about potential mistakes.
• Ground Your Feet: Feel the physical contact of your feet flat on the floor to release nervous upper-body tension.`,
    relatedLink: { text: 'Join Supportive Community Feed', view: 'community' },
    tags: ['performance anxiety', 'stage fright', 'shaky hands', 'box breathing']
  },
  {
    id: 'health-ideal-practice-break-schedule',
    category: 'Health & Breathing',
    question: 'How often should I take breaks during long practice sessions to protect my body?',
    answer: `Taking structured rest breaks maintains high mental sharpness, prevents physical fatigue, and protects joints from repetitive strain injuries.

Recommended Practice Break Rhythm:
• The 25/5 Pomodoro Rule: Practice attentively for 25 minutes, then take a mandatory 5-minute break completely away from the instrument.
• Break Activities: Stand up, walk around, stretch your hands, sip water, and rest your eyes and ears.
• Long Practice Sessions: If practicing for more than 90 minutes total daily, split your practice into distinct morning and evening sessions.`,
    relatedLink: { text: 'View Recommended Practice Schedules', view: 'learn_daily_practice' },
    tags: ['practice breaks', 'pomodoro', 'rest', 'stamina']
  },
  {
    id: 'health-diaphragmatic-breathing-exercises',
    category: 'Health & Breathing',
    question: 'What daily breathing exercises (Pranayama) increase lung capacity for flutists?',
    answer: `Practicing Pranayama yogic breathing daily expands lung stamina, diaphragm control, and tone stability on the bamboo flute.

Top 3 Pranayama Exercises for Flutists:
1. Anulom Vilom (Alternate Nostril Breathing): 5 minutes daily builds respiratory balance and calms the nervous system before practice.
2. Kapalabhati (Abdominal Breath Pulse): Trains fast abdominal muscle contractions used for executing rapid Gamaks and staccato breath strokes.
3. Dirga Pranayama (Three-Part Breath): Inhale expanding belly, then ribcage, then chest; exhale slowly in reverse order over 10 seconds to maximize usable air capacity.`,
    relatedLink: { text: 'Read Breathing & Health Blueprint', view: 'learn_basics' },
    tags: ['pranayama', 'lung capacity', 'diaphragm exercises', 'yogic breathing']
  },
  {
    id: 'health-preventing-repetitive-strain',
    category: 'Health & Breathing',
    question: 'How can I prevent wrist, thumb, and neck strain during long practice sessions?',
    answer: `Adopting ergonomic holding principles protects your joints and muscles from repetitive strain and chronic soreness.

Ergonomic Holding Principles:
• Relaxed Wrist Extension: Avoid hyper-extending or bending wrists at sharp 90-degree angles.
• Gentle Thumb Support: Rest the flute tube gently on thumb pads—never pinch or squeeze the bamboo tightly.
• Parallel Head Alignment: Keep your chin horizontal to the floor. Tilting your head downward compresses neck vertebrae and restricts airflow.
• Wrist & Shoulder Stretches: Execute gentle wrist rotations and shoulder rolls before and after every practice session.`,
    relatedLink: { text: 'View Flute Posture & Holding Blueprint', view: 'learn_basics' },
    tags: ['repetitive strain', 'wrist pain', 'ergonomics', 'neck posture']
  },
  {
    id: 'health-playing-with-asthma',
    category: 'Health & Breathing',
    question: 'Can people with asthma or respiratory conditions play the bamboo flute safely?',
    answer: `Yes! Medical experts and music therapists frequently recommend wind instruments like the bamboo flute for managing mild to moderate asthma.

Respiratory Benefits of Flute Playing:
• Natural Pulmonary Therapy: The slow, controlled diaphragmatic exhalation required for long sustained notes strengthens intercostal chest muscles and increases respiratory efficiency over time.
• Mindful Pacing: Always keep your inhaler nearby, start with short 10 to 15 minute sessions, and stop immediately if you experience shortness of breath.
• Medical Progress: Many flutists with mild asthma report noticeable improvements in daily lung function and breath endurance after regular bansuri practice.`,
    relatedLink: { text: 'Read Health Benefits of Flute Playing', view: 'learn_basics' },
    tags: ['asthma', 'respiratory health', 'lung therapy', 'flute wellness']
  }
];
